// <auto-generated />
using System;
using ExceptionFilterAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExceptionFilterAPI.Migrations
{
    [DbContext(typeof(InsuranceContext))]
    partial class InsuranceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExceptionFilterAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@gmail.com",
                            Name = "John Doe",
                            PhoneNumber = "9876543210"
                        });
                });

            modelBuilder.Entity("ExceptionFilterAPI.Models.Insurance", b =>
                {
                    b.Property<int>("InsuranceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceNumber"));

                    b.Property<float>("Balance")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayingDuration")
                        .HasColumnType("int");

                    b.Property<float>("PayoutPerMonth")
                        .HasColumnType("real");

                    b.Property<int>("ReturnDuration")
                        .HasColumnType("int");

                    b.HasKey("InsuranceNumber")
                        .HasName("PK_InsuranceNumber");

                    b.ToTable("Insurances");

                    b.HasData(
                        new
                        {
                            InsuranceNumber = 101,
                            Balance = 5000f,
                            Name = "Health Insurance",
                            PayingDuration = 12,
                            PayoutPerMonth = 1000f,
                            ReturnDuration = 24
                        },
                        new
                        {
                            InsuranceNumber = 102,
                            Balance = 2000f,
                            Name = "Car Insurance",
                            PayingDuration = 6,
                            PayoutPerMonth = 500f,
                            ReturnDuration = 12
                        });
                });

            modelBuilder.Entity("ExceptionFilterAPI.Models.Policy", b =>
                {
                    b.Property<int>("PolicyNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyNumber"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolicyNumber")
                        .HasName("PK_PolicyNumber");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InsuranceNumber");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("ExceptionFilterAPI.Models.Policy", b =>
                {
                    b.HasOne("ExceptionFilterAPI.Models.Customer", "Customer")
                        .WithMany("Policies")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExceptionFilterAPI.Models.Insurance", "Insurance")
                        .WithMany("Policies")
                        .HasForeignKey("InsuranceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("ExceptionFilterAPI.Models.Customer", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("ExceptionFilterAPI.Models.Insurance", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
